version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
    - 1.3.9
    - 1.4.0
    - 1.4.1
    - 1.5.0
  - dependency-name: react-dev-utils
    versions:
    - 11.0.1
    - 11.0.2
    - 11.0.3
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
    - 5.0.0
    - 5.1.0
    - 5.2.0
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  - dependency-name: semver
    versions:
    - 7.3.4
  - dependency-name: chalk
    versions:
    - 4.1.0
